### ISSUE TITLE
Can we add support for environment variables in the YAML?

### ISSUE THREAD

**Issue by robsyme** [ejseqera/tw-py#10]
It might be nice to add support for environment variables inside the configuration YAML file. I _think_ it might be something like:

```python
'{MY_SECRET}'.format(**os.environ))
```

after pulling the variables out of the YAML.

**Comment by robsyme** [comment]
Actually, if the variables in the YAML are being passed directly to the command-line invocation then no extra parsing is required - we just need to pass the string transparently.

**Comment by ejseqera** [comment]
This ended up just being a change to one line 🥲 

Because we're already using `shell=True` in `subprocess.Popen`, I just had to modify how we were using `shlex.quote` to escape arguments constructed for the command-line invocation to avoid environment variables so the shell would expand on them correctly. 

```
        full_cmd = " ".join(arg if arg.startswith("$") else shlex.quote(arg) for arg in command)
```
